// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNEqoJyzrsLb3spkX11P1JQO6GY26Ajgw',
    appId: '1:369319343166:web:71e27da8555ee27d408d6f',
    messagingSenderId: '369319343166',
    projectId: 'expense-tracker-4de15',
    authDomain: 'expense-tracker-4de15.firebaseapp.com',
    storageBucket: 'expense-tracker-4de15.firebasestorage.app',
    measurementId: 'G-T48HH8CWFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeowJk2ARC6WvaRCkhEFKkjwTf5ogpaz8',
    appId: '1:369319343166:android:38ade3186d3d4e49408d6f',
    messagingSenderId: '369319343166',
    projectId: 'expense-tracker-4de15',
    storageBucket: 'expense-tracker-4de15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2usyUY4iUtP0mn1Kgj74cYpBCcrcniDU',
    appId: '1:369319343166:ios:2d7e8f958523407f408d6f',
    messagingSenderId: '369319343166',
    projectId: 'expense-tracker-4de15',
    storageBucket: 'expense-tracker-4de15.firebasestorage.app',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
